ARG REGISTRY
ARG REPOSITORY
ARG VERSION
FROM ${REGISTRY}/${REPOSITORY}:${VERSION}

WORKDIR /app

RUN ln -s /databricks/python3/bin/pip /usr/local/bin/pip
# RUN /databricks/python3/bin/pip install wheel
RUN pip install wheel

COPY requirements.txt requirements.txt
# RUN /databricks/python3/bin/pip install -r requirements.txt
RUN pip install -r requirements.txt

# data build tool (DBT)
RUN ln -s /databricks/conda/envs/dcs-minimal/bin/dbt /usr/local/bin/dbt
