name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.INGENII_DOCKER_HUB_USERNAME }}
          password: ${{ secrets.INGENII_DOCKER_HUB_PASSWORD }}
      - name: Get Image Details
        id: image_details
        run: |
          echo ::set-output name=REGISTRY::$(grep '* Registry:' README.md | awk -F ':' '{print $$2}' | sed 's/ //g'))
          echo ::set-output name=REPOSITORY::$(grep '* Repository:' README.md | awk -F ':' '{print $$2}' | sed 's/ //g')
          echo ::set-output name=SOURCE_TAG::$(grep '* Current Version:' README.md | awk -F ':' '{print $$2}' | sed 's/ //g')
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.image_details.outputs.REGISTRY }}/${{ steps.image_details.outputs.REPOSITORY }}:latest, ${{ steps.image_details.outputs.REGISTRY }}/${{ steps.image_details.outputs.REPOSITORY }}:${{ steps.image_details.outputs.SOURCE_TAG }}